CREATE TABLE bill (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE bill_order (
  `bill_id` INT(11) NOT NULL,
  `food_name` VARCHAR(64) NOT NULL,
  `unit_price` DECIMAL(7,2) NOT NULL,
  `quantity` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(bill_id, food_name),
  FOREIGN KEY (bill_id) REFERENCES bill(id) ON DELETE CASCADE
);
